### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by TommasoAzz** [jjocram/italy-2018-election-data-mathematica#2]
I dataset provengono dal sito degli Open Data del Ministero dell'Interno.

I link a cui accedervi sono i seguenti:

- **Camera dei Deputati**: [https://dait.interno.gov.it/documenti/camera_2018_scrutini_italia.csv](https://dait.interno.gov.it/documenti/camera_2018_scrutini_italia.csv)
- **Senato della Repubblica**: [https://dait.interno.gov.it/documenti/senato_2018_scrutini_italia.csv](https://dait.interno.gov.it/documenti/senato_2018_scrutini_italia.csv)

**Comment by jjocram** [comment]
Capire se e come è possibile scaricarli tramite Mathematica
