### ISSUE TITLE
Funzionalità notebook

### ISSUE THREAD

**Issue by TommasoAzz** [jjocram/italy-2018-election-data-mathematica#5]
Le seguenti funzionalità vengono implementate:

- [ ] Selezione campi di input per filtro dei dati
    - [x] Regione (tendina)
    - [x] Provincia (tendina)
    - [x] Circoscrizione (tendina)
    - [x] Camera/Senato/Entrambi (checkbox) **ATTENZIONE a merge dati perché i collegi/circoscrizioni sono diversi**
    - [x] Candidato (input libero)
    - [x] Lista ovvero partito (tendina)
    - [x] Linguaggio di query ipersemplificato (NOME_CAMPO_DATI >|<|= VALORE_CAMPO_DATI (, NOME_CAMPO_DATI >|<|= VALORE_CAMPO_DATI)*)
- [x] Visualizzazione dati numerici e grafici (basati sui filtri selezionati al momento della visualizzazione)
    - [x] Elettori totali, maschi, femmine (aerogramma, testo)
    - [x] Votanti totali, maschi, femmine (aerogramma, testo)
    - [x] Per ogni lista: voti alla lista, schede bianche, schede contestate, voti non validi
    - [x] Per tutte le liste, ripartizione voti alle liste

**Comment by MickPerl** [comment]
Per i grafici, ricorrere sempre alla direttiva o primitiva `Graphics3D`, in quanto solo i suoi output supportano l'integrazione in Unity.

Vi suggerisco questo esempio per creare istogramma 3D con `Graphics3D`, piuttosto che con `Histogram3D`:

```
SeedRandom[12345];
With[{hl = 
   HistogramList[RandomVariate[NormalDistribution[0, 1], {500, 2}]]}, 
 dat = MapThread[
    Append, {Flatten[Outer[List, Sequence @@ hl[[1, All, 2 ;;]]], 1], 
     Flatten@hl[[2]]}];]
dat // Short
graph4 = Graphics3D[{Orange, 
   Cuboid[{#1, #2, 0}, {#1 + .2, #2 + .2, #3}] & @@@ dat}, 
  BoxRatios -> {1, 1, 1}, Axes -> True]
```
